name: diyet_takip
description: Diyet ve Kalori Takip Uygulamasi
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  google_mobile_ads: ^5.1.0
  flutter_local_notifications: ^17.2.2
  timezone: ^0.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true

flutter_launcher_icons:
  android: true
  image_path: "icon.png"
  adaptive_icon_background: "#B3541E"
  adaptive_icon_foreground: "icon.png"
